# Generated by Django 3.0.7 on 2020-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200625_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.IntegerField(),
        ),
    ]
