# Generated by Django 3.0.7 on 2020-06-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200625_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.FloatField(),
        ),
    ]
